### ISSUE TITLE
New release ETA?

### ISSUE THREAD

**Issue by orangesoup** [ncstate-sat/popover#104]
I'm trying to use the `autoFocus` ability, specifically disable it, but AFAIK it came in just after the last release.

Will there be a new release anytime soon, or should I just use the master branch from github?

**Comment by willshowell** [comment]
@orangesoup. I was trying to get some more changes in before another release, but see no problem with publishing it at its current state. Will do by Monday!

**Comment by orangesoup** [comment]
That would be awesome, thank you!

**Comment by willshowell** [comment]
Just released beta.5!

**Comment by orangesoup** [comment]
Thanks, works like a charm!
