### ISSUE TITLE
Move to angular-cli

### ISSUE THREAD

**Issue by shlomiassaf** [ncstate-sat/popover#123]
Hi,

Great work!

I suggest that you move to the new CLI  as your build and management tool.

I'v dont that on several libraries I have and it works great, very mature.

It will improve your build output and will make you future safe for any changes.

Here is an example:
https://github.com/shlomiassaf/ngx-modialog

That project works with library publishing, demo app and publishing the demo app to GH pages.

If you want help and/or guidance Im here.

Thanks.

**Comment by willshowell** [comment]
Hi @shlomiassaf, thanks for the heads up. It's on my todo list and it'll be great to remove the hokey build tools we have setup.
