### ISSUE TITLE
Overlay positioning/anchoring issue on iOS

### ISSUE THREAD

**Issue by Shane-E** [ncstate-sat/popover#133]
Reproduce-able at https://ncstate-sat.github.io/popover/ on an iOS device or using Simulator on a Mac.

This issue revolves around how iOS Safari has a dynamic bottom sheet within the mobile browser that hides when scrolling a page. It seems this event is not handled by the positioning service for the sat-popover, resulting in the overlay being positioned/anchored incorrectly and inconsistently if scrolling while popover is open.

Working:
<img width="559" alt="screen shot 2018-06-19 at 11 23 32 am" src="https://user-images.githubusercontent.com/7751783/41607421-ffbe125a-73b3-11e8-8e42-b7a081aec399.png">

Broken:
<img width="559" alt="screen shot 2018-06-19 at 11 23 43 am" src="https://user-images.githubusercontent.com/7751783/41607440-08e40c4a-73b4-11e8-864d-70eaab3df25e.png">

**Comment by Shane-E** [comment]
The same thing also happens for android devices after scrolling as the navigation bar at the top disappears

**Comment by willshowell** [comment]
Yeah I'm afraid that's a problem in the cdk's overlay service (as I saw you noted in https://github.com/angular/material2/issues/9334).

I know the material folks have been looking into it for a while without much of an update (https://github.com/angular/material2/issues/6341), but if I can find some time, I'll try to dig into it as well.

**Comment by willshowell** [comment]
@Shane-E the next patch release of the CDK should have a fix for this: https://github.com/angular/material2/pull/12119

**Comment by Shane-E** [comment]
This has been fixed.
