### ISSUE TITLE
How can be show popover in full screen mode? I'm using Angular 6.

### ISSUE THREAD

**Issue by keshav078** [ncstate-sat/popover#148]

**Comment by julianobrasil** [comment]
@keshav078, a popover is different from a dialog in that it's anchored on a specific component that works as a point where it should be shown.

But you can overcome that in some ways. You can center a div on the page and use it as an anchor to the popover. Or you can use any element and use regular CSS to show the component you wish to be shown in the center. In both cases you could set the width and height to full screen (100vw/vh).

**Comment by willshowell** [comment]
Like @julianobrasil said, full screen behavior isn't a great fit for this component. Its primary purpose is to anchor onto some element and stay attached to it as long as it's open. You may be interested in the [`MatDialog`](https://material.angular.io/components/dialog/overview) instead.

Here's an example along the lines of what Juliano is describing - I hope it helps!

https://stackblitz.com/edit/sat-popover-issues-wpa2ov?file=app%2Fapp.component.html

**Comment by keshav078** [comment]
Yeah! I understand. Thanks.

**Comment by fxck** [comment]
There is a usecase for something like this, at some point (mobile resolutions) it stops making sense to try to anchor to an element and rather switch to fullscreen, dialog-like pop. 

For this I've created a wrapper which includes both dialog and pop, ngTemplateOutlets content to both and open one or the other depending on resolution. But having this part of pop would be so so much cleaner.

**Comment by julianobrasil** [comment]
Geez, @fxck! Commenting on 5 years old closed issues must be against the rules :joy: I've been working with React for almost 3 years and I definitely miss the angular community (and angular itself)
