### ISSUE TITLE
feature: add [satPopoverHover] directive

### ISSUE THREAD

**Issue by willshowell** [ncstate-sat/popover#152]
Add SatHoverDirective from @Abrissirba's stackblitz and publish to users as a convenient utility

https://stackblitz.com/edit/sat-popover-examples-esomkk?file=app%2Fsat-hover.directive.ts

Minor changes to be made to that version

- rename directive to `SatPopoverHoverDirective`
- set the selector to `[satPopoverHover]`
- DI the `SatPopoverAnchor` so that child elements of the anchor can be used as mouseover toggles
- coerce the input to a number to support

**Comment by astra1** [comment]
@willshowell Hello, sir! Could you please extend satPopoverDirective options with visibility property? Or there is some other way to accomplish this (without ng-template + ng-if or custom mouseenter)?

**Comment by willshowell** [comment]
@astra1 could you expand on what you need? Since the popover itself doesn't have any styling, you should be able to set the visibility of your popover contents however you wish
