### ISSUE TITLE
Update to angular 8

### ISSUE THREAD

**Issue by beyondtheobservableuniverse** [ncstate-sat/popover#159]
Hi

Please update Angular packages to version 8.

`Package "@ncstate/sat-popover" has an incompatible peer dependency to "@angular/cdk" (requires "^7.0.0", would install "8.0.0").`

**Comment by pgkehle** [comment]
Yes, that is on our roadmap.  👍

**Comment by sunithzysk** [comment]
+1 Please update to angular 8

**Comment by emrhesen** [comment]
> +1 Please update to angular 8

+1

**Comment by pgkehle** [comment]
See https://github.com/ncstate-sat/popover/pull/160.  Working to release v3.3.0

**Comment by pgkehle** [comment]
Released v3.3.0.  Minor changes in master that are not being released.

**Comment by beyondtheobservableuniverse** [comment]
Thank you!
