### ISSUE TITLE
Breaking change between 3.2.0 and 3.3.0

### ISSUE THREAD

**Issue by BigGillyStyle** [ncstate-sat/popover#164]
I don't know if you intend to follow semver on this project or not, but you just introduced a breaking change ( which you documented here: https://github.com/ncstate-sat/popover/blob/master/CHANGELOG.md#breaking-changes-aka-features ) with a **minor** version release of your library.  I found this out locally on an Angular 7 project (that is not quite ready to upgrade to Angular 8) when I did a `yarn upgrade` locally.  I got the expected warning (about the wrong version of Angular), as yarn upgraded this library from 3.2.0 to 3.3.0.

This is not really a big deal to me, as I can of course lock down the version to 3.2.0...but really I think it's "JS community convention" to introduced breaking changes only in a major version release.

**Comment by pgkehle** [comment]
That's fair.  Yes, it should be moved to v4.0.0 because of the breaking changes.

**Comment by pgkehle** [comment]
Fixed via #165

**Comment by willshowell** [comment]
@pgkehle I might suggest deprecating 3.3 so users get a warning about the breaking changes if they try to upgrade like @BigGillyStyle did.

https://docs.npmjs.com/cli/deprecate

**Comment by pgkehle** [comment]
Great call @willshowell.

![Screen Shot 2019-06-28 at 4 22 54 PM](https://user-images.githubusercontent.com/798015/60369272-10235680-99c1-11e9-92da-e614f216b5f1.png)
