### ISSUE TITLE
Mobile view - popover is outside screen

### ISSUE THREAD

**Issue by BojanKogoj** [ncstate-sat/popover#179]
On mobile view popover doesn't fit inside the screen, but overflows even with `max-width: 100%`. I can see CDK is controling position and size, but is there a known way to fix it?

![image](https://user-images.githubusercontent.com/634075/75691893-0024ea80-5ca5-11ea-9979-026496400776.png)

Example https://stackblitz.com/edit/ncstate-sat-popover-examples-tsfnu1

**Comment by nsnayp13** [comment]
You are seted .info-wrapper width:400px in simple-example. May be u should set max-width or some else.

**Comment by BojanKogoj** [comment]
I also set `max-width: 100%;`, it doesn't matter. As soon as there is width, max-width doesn't matter for some reason.

**Comment by nsnayp13** [comment]
I set width: auto; width: auto; In browser it works. But parent component position set left: -3px;
```
.info-wrapper {
  @include elevation();
  padding: 16px;
  background: white;
  width: auto;
  width: auto;
  line-height: 28px;
}
```

I

**Comment by julianobrasil** [comment]
I think I'm this case you'll have to take care of repositioning it by your self. If I remember right, in the past Angular material guys used to switch from overlay to mat-dialog in small devices on the datepicker component. Later, they abandoned the dialog approach for something else you could check out on their project to see what it is.
