### ISSUE TITLE
doesn't animate *IN* on the second run, just appears

### ISSUE THREAD

**Issue by fxck** [ncstate-sat/popover#205]
I just noticed after years 

https://stackblitz.com/edit/ncstate-sat-popover-examples-bxikxm?file=app%2Fhover-example%2Fhover-example.component.ts

especially noticable when you increase duration / delay

**Comment by fxck** [comment]
looks like duplicate :) https://github.com/ncstate-sat/popover/issues/194

**Comment by pgkehle** [comment]
Yes duplicate. Could use some help looking into the issue.
