### ISSUE TITLE
Feature: support more configurability for the focus trap

### ISSUE THREAD

**Issue by willshowell** [ncstate-sat/popover#22]
* Should popovers with no focusable elements steal the focus anyway? Or should `cdkFocusInitial` just be documented?
* Should users be able to disallow focus trapping? Maybe a tooltip-like popover has a focusable field but shouldn't be autofocused? Maybe a popover has some inputs but it's auxiliary and shouldn't steal focus from the page?

**Comment by willshowell** [comment]
I'm considering making this opt-in with a `focusable` input.

Basically, if `focusable == true`, then focus is trapped and the first focusable element is automatically focused on open. If there is no focusable elements, the overlay may be able to also be focused. https://github.com/angular/material2/pull/8051

If focusable is false, by default, then the user can be confident that know weird behavior will happen with their tooltip.

**Comment by julianobrasil** [comment]
Never thought a single component could have so many applications. We almost have a PDK 😄 .

**Comment by willshowell** [comment]
Lol, we have to be careful not to accidentally reinvent `cdk/overlay`.
