### ISSUE TITLE
Clickable content inside popover and hover trigger

### ISSUE THREAD

**Issue by omygoodness** [ncstate-sat/popover#232]
Is there a way to force the popover to stay open to be able to click on the content inside it (link for example) when opened on hover?
I used `[satPopoverHover]` to open popover on hover. 

[Live example on stackblitz](https://stackblitz.com/edit/angular-ivy-kctmvq?file=src/app/app.component.html)

**Comment by gianmd** [comment]
@omygoodness did you find any solution?

**Comment by isaackehle** [comment]
How is this looking with the updated packages?

**Comment by omygoodness** [comment]
> @omygoodness did you find any solution?

It was a long time ago. We went with a custom solution in the end. I didn't check it with any new version
