### ISSUE TITLE
Angular 15 was released

### ISSUE THREAD

**Issue by fidian** [ncstate-sat/popover#270]
When installing this package with Angular 15 libraries, the peer dependency doesn't work because it's looking for ^14.0.4.

**Comment by Igor2017** [comment]
I changed dependencies in package.json file on Angular 15.
https://github.com/Igor2017/popover/commit/8db179c032856e17fe583f0e396910da25219ae6
Tests break, but the demo works well, no errors.

**Comment by dechamps** [comment]
[Make that Angular 16 now.](https://blog.angular.io/angular-v16-is-here-4d7a28ec680d)

**Comment by Igor2017** [comment]
This works in Angular 16
```
npm i @igor2017/sat-popover
```

**Comment by fabichacon** [comment]
Is there going to be a new release with this fix in any time soon?

**Comment by isaackehle** [comment]
> > Is there going to be a new release with this fix in any time soon?
> 
> Please see the Ownership Discussion, #255. I dont believe the owner still has access to this repository so it _may be_ abandonded.

I am still around, though I’ve been letting the SAT department lead the answers. 
I’ll try to squirrel some time today to get a release out.

**Comment by fidian** [comment]
It's possible that you could compile this for Angular 16 using Ivy, then ignore it for several versions by removing the peer dependencies. This approach could have a much longer period where it wouldn't need maintenance.

**Comment by isaackehle** [comment]
> It's possible that you could compile this for Angular 16 using Ivy, then ignore it for several versions by removing the peer dependencies. This approach could have a much longer period where it wouldn't need maintenance.

If you can pull together a PR that I can review, and if others can give thumbs up/down here, sure!

**Comment by fidian** [comment]
Sorry, I'm familiar with Angular libraries that are built as separate projects. Those allow for multiple builds, such as one for the live demo and one for the library itself. Using that structure, the library can have a package.json that does not mention Angular. My advice is not applicable to this structure.

**Comment by isaackehle** [comment]
Handled via #287 #286 #285
