### ISSUE TITLE
Angular 18 was released

### ISSUE THREAD

**Issue by fidian** [ncstate-sat/popover#298]
Any chance this project can be updated to work with Angular 18? Or maybe make it "versionless" so updates don't need to happen with each release?

**Comment by isaackehle** [comment]
There's an MR out for it already, see https://github.com/ncstate-sat/popover/pull/297.
Regarding versionless, I do not have experience with this. My gut says this could lead to breaking changes that are not caught without manual updates to this package. 

Does anyone else have a thought?  @wjaspers ?

**Comment by isaackehle** [comment]
Merged #297
