### ISSUE TITLE
Two triggers firing the same popover

### ISSUE THREAD

**Issue by julianobrasil** [ncstate-sat/popover#64]
I don't know if this is a bug or a design choice, but it would be nice if I could have more than one trigger firing the same popover. Currently, the popover is attached to just one of them (the last one to be rendered in the page)

![image](https://media.giphy.com/media/3ov9jZq8jmBwx1y6eA/giphy.gif)

In the image above I expected the popover to be next to each word "Legenda"

**Comment by willshowell** [comment]
Currently there is an assumed one-to-one relationship between anchors and popovers. You can mostly get around it by using the anchor's open/close api, 

https://stackblitz.com/edit/sat-popover-examples-hqtkwx?file=app%2Fhover-example%2Fhover-example.component.ts (see the hover example)

but it breaks as soon as you want the popover to be open in two places at once. Nevertheless, I think this is a valid feature and I'll work on trying to figure out a good api for it.

What's your use-case? Are you trying to avoid several `sat-popover` definitions?

**Comment by julianobrasil** [comment]
Oh, in that case (I haven't noticed there was an `exportAs` in the anchor), I think the feature I'm suggesting is already fulfilled. Now the presence of an anchor in this component makes _a lot_ of sense. 

Yes, I'm trying to avoid code repetition. Though I could build up a compontent to encapsulate the popover or do it with a wrapper method, and avoid it, it seems that would polute the declarations array of my feature module with a such simple thing used in just one part of the app). And again, the exported `SatPopoverAnchor` solves it in a much more elegant way.

About opening several popover's with a single anchor... well, it's not so common. I cannot think right now of a convincent use case to have it. Maybe an assistant helper that could show to the user where stuff could be found in a page as the user pass the mouse over the helper text, like: "Whenever you need help, there'll be a question mark near the topics to bring you some cool explanations" and when the user passes the mouse over the expression "question mark", that would fire some popovers all over the page where there were question marks showing their helper texts... OMG, this is a terrible example 😄 

But the use case that lead me to open this issue is valid. The app summary: 
- "_In our university, we use indicators to mesure the performance of virtually everything. Every department works with its particular indicators (an possibly people in each department have his/her own indicators). The app allows everyone to just create indicators. It calculates it, shows history, charts, allows for the creation of actions plans when an indicator doens't reach some aimed value etc._"

Well, I have a table in this app that can grow a lot, depending on the page size chosen by the user (I have a pagination component attached to it). This table has some information, like the colors of the rows, and some icons in some cells in each row that are shown depending on some cell values on that row. So I need some kind of legend to explain these parts of the table structure to the user. I don't want this legend to take space away of the screen, because the page is already full of information, so I decided to try out the popover to show the legend. Here is why I have a copy of it in the same page: If I put the legend on top and the user chooses a page of 50 rows, he will not see the legend whenever he scrolls down the page to look at the lower rows. It would force him to scoll up the page to see the legend, hover the pointer over it and see the legend. So I decide to repeat the legend (as the pagination control) at the top and the bottom of the table to reduce the scrolling needs.

I don't know if this approach is good enough, but I'll test it for some days. A user is an evil creature that has the hability to find out hidden erros in any system and complains very quickly when the usability is not good enough.

**Comment by willshowell** [comment]
A more robust solution, that doesn't require you to declare another component, would be to reuse the popover content with an `ng-template`

```html
<ng-template #tooltip>
  <!-- Whatever you want to place inside your tooltip -->
</ng-template>

<sat-popover #a xPosition="after" [overlapAnchor]="false">
  <ng-container [ngTemplateOutlet]="tooltip"></ng-container>
</sat-popover>

<sat-popover #b xPosition="after" [overlapAnchor]="false">
  <ng-container [ngTemplateOutlet]="tooltip"></ng-container>
</sat-popover>
```

https://stackblitz.com/edit/sat-popover-examples-5zk6af

**Comment by willshowell** [comment]
One tangentially related feature I could imagine would be to dynamically define and swap the popovers that are attached to any given anchor. Currently, it must be defined at view init.

```html
<div [satPopoverAnchorFor]="getCurrentPopover()">Anchor</div>

<sat-popover *ngFor="let i of [1, 2, 3]">Popover {{ i }}</sat-popover>
```

```ts
@ViewChildren(SatPopover): popovers: QueryList<SatPopover>;

currentPopoverIndex = 2;

getCurrentPopover(): SatPopover {
  return this.popovers.find((p, i) => i === this.currentPopoverIndex);
}

**Comment by abcd-ca** [comment]
based on this thread I got the hover example working on click in case it helps someone else: 

https://stackblitz.com/edit/sat-popover-examples-eepgqz?file=app/hover-example/hover-example.component.ts

**Comment by LoveenDyall** [comment]
So how do I reference a popover element if it's initialised inside *ngFor?

**Comment by willshowell** [comment]
@LoveenDyall the easiest way would be inside the local context of the ngFor. Otherwise, `@ViewChildren(SatPopover)` would work if you're trying to get a popover at a specific index.
