### ISSUE TITLE
Feat: support `start` and `end` for positions

### ISSUE THREAD

**Issue by aitboudad** [ncstate-sat/popover#68]
hi, I would like to display the popover beneath the element, right now the `xPosition` only support three options ('before', 'center', 'after') which doesn't cover my use-case.

**Comment by willshowell** [comment]
I don't think I'm clear on what `xPosition="start"` would do. To position it beneath the element, you can use `yPosition="below"`.

```html
<button [satPopoverAnchorFor]="p" (click)="p.toggle()">Toggle</button>

<sat-popover #p yPosition="below" [overlapAnchor]="false">
  <div class="popover-wrapper">
    Hello!
  </div>
</sat-popover>
```

![screen shot 2017-11-02 at 9 34 19 am](https://user-images.githubusercontent.com/6475576/32328395-3bed4ede-bfb0-11e7-93fe-4612b0d08da4.png)

https://stackblitz.com/edit/sat-popover-issues-pmaqwy?file=app/app.component.html

**Comment by aitboudad** [comment]
@willshowell I would like to have something like:
![selection_105](https://user-images.githubusercontent.com/1753742/32328780-f4b8a5ea-bfd2-11e7-8b77-43afbe4597c1.png)

instead of:
![selection_104](https://user-images.githubusercontent.com/1753742/32328796-fe7151ae-bfd2-11e7-8b5b-a8b0fe7a20e9.png)

**Comment by aitboudad** [comment]
the first one sound better to me

**Comment by julianobrasil** [comment]
@willshowell, what about Changi grande `xPosition` to `horizontalAlign` (and do the same to `yPosition` => `verticalAlign`)? Or anything that doesn't depend on user's previous knowledge about cartesian Axis.

**Comment by willshowell** [comment]
@julianobrasil I can dig it. Do you have any strong opinion about `align` vs `pos` vs `position`? I'd also be interested in adding aliases to keep the api tighter, if it isn't too confusing.

```ts
horizontalPos: 'before' | 'start' | 'center' | 'end' | 'after';
verticalPos:   'above'  | 'start' | 'center' | 'end' | 'below';

xPos // alias to horizontalPos
yPos // alias to verticalPos
```

**Comment by aitboudad** [comment]
@willshowell
> Can you describe your use-case?

I would like to use it inside an input field, something like datepicker for material
![selection_106](https://user-images.githubusercontent.com/1753742/32341721-31dfe7c6-bff6-11e7-8f6d-0532fb9320fb.png)
