### ISSUE TITLE
feat(rename @Input): Rename xPosition and yPosition

### ISSUE THREAD

**Issue by julianobrasil** [ncstate-sat/popover#70]
As stated in https://github.com/ncstate-sat/popover/issues/68#issuecomment-341474256, using **_x_** and **_y_** in the name of `@Input` properties, although technically understandable, may require some previous knowledge on geometry from the user (cartesian axis).

As a suggestion:
- `xPropertyName` => `horizontalPropertyName`
- `yPropertyName` => `verticalPropertyName`

> Do you have any strong opinion about align vs pos vs position? 

No. I just think using **_x_** and **_y_** isn't so natural for some app developers as **_horizontal_** and **_vertical_**. But I'd go with **_align_**.

> I'd also be interested in adding aliases to keep the api tighter, if it isn't too confusing.

Well... thinking of saving bytes in the final bundle, maybe shorter names are better. I'm not sure about how efficient is the minifying process concerning the `@Input` variables. Yes, it can be a little bit confusing having two `@Input` properties to do the same thing (at first), but I also think that it can be easely explained in docs.

**Comment by willshowell** [comment]
Thanks for separating the issue. My intention with aliases wasn't for smaller bundle, but for template cleanliness. It's personal preference, of course, but I like to break lines around 90-100 characters, so keeping input names as minimal as they can be while still being descriptive is important.

```html
<!-- Proposed that both would be allowed and equal -->
<sat-popover #p hasBackdrop horizontalAlign="start" verticalAlign="below">
<sat-popover #p hasBackdrop xPos="start" yPos="below">
```

But I also see the point that having aliases can be confusing. And it's not like `openTransition=""` or `scrollStrategy=""` are particularly short. Plus, losing `overlapAnchor` will save space anyway. I also like `horizontalAlign` since it matches flexbox's `align-items`.

I guess in conclusion, I like the proposal! I just want to chew on it a bit more before making the change.

**Comment by willshowell** [comment]
Oh another consideration is that I'd like to add offset support soon. So it would probably have to match

```html
<sat-popover #p
    horizontalAlign="after"
    verticalAlign="above"
    horizontalOffset="16"
    verticalOffset="16">
  <my-tooltip></my-tooltip>
</sat-popover>
```

vs. something like,

```html
<sat-popover #p
    xAlign="after"
    yAlign="above"
    xOffset="16"
    yOffset="16">
  <my-tooltip></my-tooltip>
</sat-popover>
```

So this kind of makes me swing back towards providing an alias but keeping `*Align` for both. It would probably be described in the docs to use `horizontal|vertical` but with a note saying there is an `x|y` shorthand.

**Comment by julianobrasil** [comment]
If we think the position we'll be set relative to another component,  than `align` makes more sense (two components will be _aligned_ in some way).

We can also think of **_h_** and **_v_** as an alternative to **_x_** and **_y_**. It is not so clear as **_horizontal_** and **_vertical_**, but it steps away from axis concepts.

**Comment by willshowell** [comment]
I've given this some thought and think it would be best to go with `horizontalAlign` with `xAlign` as an alias. The README would look like this

----

### Positioning

By default, the popover will appear centered over the anchor. If you instead want the popover
to appear below the anchor:

```html
<sat-popover #contactPopover verticalAlign="below">
  <!-- ... -->
</sat-popover>
```

You can use the following to position the popover around the anchor:

| Input                | Type                                                              | Default  |
|---------------|-------------------------------------------|----------|
| `horizontalAlign` | 'before' \| 'start' \| 'center' \| 'end' \| 'after' | 'center' |
| `verticalAlign`     | 'above'  \| 'start' \| 'center' \| 'end' \| 'below' | 'center' |

For convenience, you can also use `xAlign` and `yAlign` as shorthand for `horizontalAlign` and `verticalAlign`, respectively.
