### ISSUE TITLE
Handle popovers near edge of viewport

### ISSUE THREAD

**Issue by rosslavery** [ncstate-sat/popover#72]
First of all, thank you for your great work on this component, it's exactly what we've needed for a while now.

Right now if a popover is opened near the edge of the viewport, it opens without taking that into account.

It seems to prioritize opening over the anchor rather than ensure it's always visible.

I understand there are inputs to control the positioning manually, but in a dynamically generated list, there is the potential for an item to be on multiple sides of the viewport.

MatMenu seems to handle this, not sure if it's part of CDK, or custom code for Material: https://material.angular.io/components/menu/overview

**Comment by willshowell** [comment]
Glad to hear it's helping! Here's a demo of the issue (for my own reference later)

https://stackblitz.com/edit/sat-popover-issues-uwmunm?file=app%2Fapp.component.html

The cdk's positioning strategies have some planned upgrades, but who knows when they'll be available. Until then, I think this is something that can be fixed if we more intelligently configure fallback positions. 

https://github.com/ncstate-sat/popover/blob/dbb5211d977d8de76cfcdb3ec436121d7b9a0713/src/lib/popover/popover-anchor.directive.ts#L282-L332

It works alright if you set the x and y positions somewhere other than center, but it doesn't do much if both x and y are 'center'.
