### ISSUE TITLE
Module not found: Error: Can't resolve 'rxjs/operators/takeUntil'

### ISSUE THREAD

**Issue by JeffPlummer** [ncstate-sat/popover#83]
It looks like a couple files reference 'rxjs/operators/...' (with an 's').  At least with the newer version or rxjs has items in 'rxjs/operator/..." (no 's' in 'operator').

**Comment by willshowell** [comment]
Where are you seeing this error? Can you provide a reproduction?

Lettable operators in rxjs > 5.5 are imported from `rxjs/operators/...`.

https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md#usage

**Comment by willshowell** [comment]
@JeffPlummer I haven't been able to reproduce. If you can provide more information, I'll be happy to reopen.
