### ISSUE TITLE
ERROR TypeError: this._overlayRef.keydownEvents is not a function

### ISSUE THREAD

**Issue by LucasFrecia** [ncstate-sat/popover#95]
I am trying to use this library but I get this error and do not want to mess with the library code so I hope I can get some help here and get it working.

I actually compile the whole application without any problem, but when I call the reference to call popover, It breaks and I get the following stack on my console:

> ERROR TypeError: this._overlayRef.keydownEvents is not a function
>     at SatPopoverAnchor.webpackJsonp.../../../../@ncstate/sat-popover/@ncstate/sat-popover.es5.js.SatPopoverAnchor._subscribeToEscape (sat-popover.es5.js:1042)
>     at SatPopoverAnchor.webpackJsonp.../../../../@ncstate/sat-popover/@ncstate/sat-popover.es5.js.SatPopoverAnchor.openPopover (sat-popover.es5.js:899)
>     at SafeSubscriber._next (sat-popover.es5.js:997)
>     at SafeSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:239)
>     at SafeSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next (Subscriber.js:186)
>     at Subscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next (Subscriber.js:127)
>     at Subscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next (Subscriber.js:91)
>     at TakeUntilSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next (Subscriber.js:127)
>     at TakeUntilSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next (Subscriber.js:91)
>     at Subject.webpackJsonp.../../../../rxjs/_esm5/Subject.js.Subject.next (Subject.js:56)

The error points to the file **popover/src/lib/popover/popover-anchor.directive.ts** in line 209:

```
  /** Close popover when escape keydown event occurs. */
  private _subscribeToEscape(): void {
    this._overlayRef
      .keydownEvents()
```

Here is my package.json in case it helps:

```
{
  "name": "liquidaciones",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "5.1.1",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/common": "5.1.1",
    "@angular/compiler": "5.1.1",
    "@angular/core": "5.1.1",
    "@angular/forms": "5.1.1",
    "@angular/http": "5.1.1",
    "@angular/material": "2.0.0-beta.12",
    "@angular/platform-browser": "5.1.1",
    "@angular/platform-browser-dynamic": "5.1.1",
    "@angular/router": "5.1.1",
    "@ncstate/sat-popover": "^1.0.0-beta.4",
    "@ngrx/core": "^1.2.0",
    "@ngrx/store": "^4.0.3",
    "core-js": "^2.5.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.5.2",
    "typescript": "^2.4.2",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "1.6.1",
    "@angular/compiler-cli": "^5.1.1",
    "@angular/language-service": "^5.1.1",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
```
If you need more info please let me know! Hope someone can help mates!

**Comment by willshowell** [comment]
Hey @LucasFrecia, the `keydownEvents()` method was added to a newer version of `@angular/cdk` than you are using. I highly recommend upgrading `@angular/cdk` and `@angular/material` to ^5.0.0.

If you can't for any reason, you can also try downgrading `@ncstate/sat-popover` to 1.0.0-beta.1. The documentation for that version is here:

https://github.com/ncstate-sat/popover/tree/v1.0.0-beta.1

**Comment by LucasFrecia** [comment]
that clears it! Right now I am using it without any troubles I removed the function and subscription from your code and I can use it without any troubles... I will update cdk and material however I can´t do it right now. 

Thanks for your answer!
