### ISSUE TITLE
Feature:  Allow the tooltips to show when the fab is clicked.

### ISSUE THREAD

**Issue by ajspeller** [ncstate-sat/popover#96]
Current Functionality:

The tooltips appear for an action during the mouseenter event and disappear during the mouseleave event.

Suggested Feature:

A configuration that would allow all of the tooltips to display when the fab is toggled open.

Example:

The Inbox app by Google.

**Comment by willshowell** [comment]
Hey @ajspeller - currently there isn't a great way to open a popover (in this case, the tooltip) before it exists. For the functionality in Google Inbox, you could do one of the following:

1. Don't use tooltips, and just add static markup next to the mini fabs:

    https://stackblitz.com/edit/sat-popover-issues-btzcmx

2. Open the tooltips after the speed dial completes its opening animation:

    https://stackblitz.com/edit/sat-popover-issues-yhgbgy

**Comment by ajspeller** [comment]
Thank you for the suggestions.  I will give both a try.

**Comment by willshowell** [comment]
@ajspeller I'm going to close this - feel free to open another issue or comment further if you run into any other problems.
